# fly.toml app configuration file generated for recurringly-backend on 2024-01-19T16:50:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recurringly-backend"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  DB_HOST = "recurringly-postres.flycast"
  DB_PORT = 5432
  DB_NAME = "recurringly_backend"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
